### ISSUE TITLE
Implement basic dependencies between resources

### ISSUE THREAD

**Issue by r3nic1e** [chartwave/chartwave#4]
Implement references for already-known expressions. Probably using https://github.com/tidwall/sjson and https://github.com/tidwall/gjson

```yaml
// deployment my
kind: apps
metdata:
  name: my

// service my
metadata:
  name: $my.metadata.name
```
