### ISSUE TITLE
Implement internal resource dependencies

### ISSUE THREAD

**Issue by r3nic1e** [chartwave/chartwave#5]
```yaml
kind: apps
metdata:
  name: my
  annotations:
    app: $this.metadata.name
    instance: $this.metadata.app
```

**Comment by zhilyaev** [comment]
default chartwave like `helm create my-chart`

```yaml
name: my-release
namespace: my
version: latest # doubtful, but ok


selectorLabels: &selectorLabels
  app.kubernetes.io/instance: {{ $name }}
  app.kubernetes.io/name: {{ $name }}

labels: &labels
  <<: *selectorLabels
  app.kubernetes.io/version: {{ $version }}
  app.kubernetes.io/managed-by: chartwave
  chartwave.app/version: v0.0.1
  

objectMeta:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    <<: *labels


# Workloads
image:
  registry: docker.io
  repository: nginx
  tag: {{ $version }}


container:
  name: {{ $name }}
  image: {{ image $image }}

serviceAccounts:
  $name: {}

pod:
  spec:
    serviceAccountName: {{ $serviceAccounts.$name }}


deployment:
  spec:
    selector:
      matchLabels:
        <<: *selectorLabels
    revisionHistoryLimit: 2
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        
deployments:
  $name: {}
  

# autoscaling
crossVersionObjectReference:
  apiVersion: apps/v1
  kind: Deployment
  name: {{ $deployments.$name }}

hpa:
  spec:
    MinReplicas: 1
    MaxReplicas: 100

HPAs:
  $name: {}
  
# Service
service:
  spec:
    type: ClusterIP
    selector:
      <<: *selectorLabels
    ports:
      - name: http
  
servicePort:
  port: 8080
  targetPort: http
  protocol: TCP
  name: http

services:
  $name: {}

# ingress
ingress:
  spec:
    rules:
      - host: my.cluster.local
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service: {{ $services.$name }}

ingresses:
  $name: {}
```
