### ISSUE TITLE
Implement Chartfile

### ISSUE THREAD

**Issue by r3nic1e** [chartwave/chartwave#6]
```dockerfile
FROM scratch

METADATA keywords=[blabla,bla2] home=https://dev.null sources=[] maintainers=[] appVersion=0.1.0
ADD templates/
```

```dockerfile
FROM bitnami/support as helpers

###
FROM bitnami/nginx:13.2.11

REMOVE deployment.yaml
ADD templates/deployment-fixed.yaml
ADD --from=helpers helper.yaml
```

**Comment by zhilyaev** [comment]
```yaml
# METADATA
name: my-release
namespace: {{ $name }}
notes: "Successful deploy!"
description: "this release managed by helmwave"


selectorLabels: &selectorLabels
  app.kubernetes.io/instance: {{ $name }}
  app.kubernetes.io/managed-by: chartwave

labels:
  env: qa
  <<: *selectorLabels

pod: # default options for all pods
  priorityClassName: {{ $labels.env }}

envs:
  GREETING: HELLO

image: # default image
  registry: docker.io
  repository: nginx
  tag: latest

customImage:
  registry: localhost
  repository: test
  tag: latest

container: # default options for all containers
  image: {{ image $customImage }} # overrive $image to $customImage, transform $customImage to localhost/test:latest

# COLLECTIONS
deployments:
  app: {} # deployment's name is my-release-app
  $name: {} # deployment's name is my-release
  useCustomConfigMap:
    spec:
      template:
        metadata:
          annotations:
            checksum/configMap.customEnvs: {{ hash $configMaps.customEnvs }}
      
      spec:
        containers:
          - name: app
            envFrom:
            - configMapsRef: {{ $configMaps.customEnvs }}
          
  
HPAs:
  app: {} # by default ref $HPAs.app to $deployments.app
  custom:
    spec:
      scaleTargetRef: {{ $deployments.app }}
  $name: # hpa's name is my-release
    spec:
      scaleTargetRef:
        name: {{ $deployments.$name.name }} # this value is default
  

statefulSets:
  app: {}

configMaps:
  customEnvs:
    data:
      HELLO: "World"

secrets:
  CustomEnvs:
    data:
      TOKEN: "my-secret-token"


```
